BEGIN;

CREATE TABLE ROL (
  id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE AREA (
  id_area INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE USUARIO (
  id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  estado BOOLEAN NOT NULL DEFAULT true,
  id_rol INTEGER NOT NULL REFERENCES ROL(id_rol)
);

CREATE TABLE EMPLEADO (
  id_empleado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cedula VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(100) NOT NULL,
  apellido VARCHAR(100) NOT NULL,
  telefono VARCHAR(30),
  email VARCHAR(255),
  activo BOOLEAN NOT NULL DEFAULT true,
  id_area INTEGER NOT NULL REFERENCES AREA(id_area),
  id_usuario INTEGER NOT NULL UNIQUE REFERENCES USUARIO(id_usuario)
);

CREATE TABLE JORNADA (
  id_jornada INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  hora_inicio TIME NOT NULL,
  hora_fin TIME NOT NULL,
  horas_maximas NUMERIC(5,2) NOT NULL CHECK (horas_maximas > 0)
);

CREATE TABLE HORARIO (
  id_horario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NOT NULL,
  id_empleado INTEGER NOT NULL REFERENCES EMPLEADO(id_empleado),
  id_jornada INTEGER NOT NULL REFERENCES JORNADA(id_jornada),
  CHECK (fecha_inicio <= fecha_fin)
);

CREATE TABLE ASISTENCIA (
  id_asistencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha DATE NOT NULL,
  hora_entrada TIMESTAMP WITH TIME ZONE,
  hora_salida TIMESTAMP WITH TIME ZONE,
  id_empleado INTEGER NOT NULL REFERENCES EMPLEADO(id_empleado),
  UNIQUE (id_empleado, fecha)
);

CREATE TABLE INCONSISTENCIA (
  id_inconsistencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(50) NOT NULL,
  descripcion TEXT NOT NULL,
  fecha_hora TIMESTAMP WITH TIME ZONE NOT NULL,
  estado VARCHAR(30) NOT NULL DEFAULT 'pendiente',
  id_asistencia INTEGER NOT NULL REFERENCES ASISTENCIA(id_asistencia)
);

CREATE TABLE JUSTIFICACION (
  id_justificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion TEXT NOT NULL,
  fecha_envio TIMESTAMP WITH TIME ZONE NOT NULL,
  estado VARCHAR(30) NOT NULL DEFAULT 'pendiente',
  id_inconsistencia INTEGER NOT NULL REFERENCES INCONSISTENCIA(id_inconsistencia)
);

CREATE TABLE PERMISO (
  id_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NOT NULL,
  motivo TEXT,
  estado VARCHAR(30) NOT NULL DEFAULT 'pendiente',
  id_empleado INTEGER NOT NULL REFERENCES EMPLEADO(id_empleado),
  CHECK (fecha_inicio <= fecha_fin)
);

CREATE TABLE VACACION (
  id_vacacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NOT NULL,
  estado VARCHAR(30) NOT NULL DEFAULT 'pendiente',
  id_empleado INTEGER NOT NULL REFERENCES EMPLEADO(id_empleado),
  CHECK (fecha_inicio <= fecha_fin)
);

CREATE TABLE COBERTURA (
  id_cobertura INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha DATE NOT NULL,
  estado VARCHAR(30) NOT NULL DEFAULT 'pendiente',
  id_inconsistencia INTEGER NOT NULL REFERENCES INCONSISTENCIA(id_inconsistencia),
  id_empleado_sustituto INTEGER NOT NULL REFERENCES EMPLEADO(id_empleado)
);

CREATE TABLE AUDITORIA (
  id_auditoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entidad VARCHAR(50) NOT NULL,
  id_entidad INTEGER,
  accion VARCHAR(80) NOT NULL,
  descripcion TEXT NOT NULL,
  datos JSONB NOT NULL DEFAULT '{}'::jsonb,
  fecha_hora TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_usuario INTEGER REFERENCES USUARIO(id_usuario) ON DELETE SET NULL
);

CREATE INDEX idx_horario_empleado_periodo ON HORARIO (id_empleado, fecha_inicio, fecha_fin);
CREATE INDEX idx_asistencia_empleado_fecha ON ASISTENCIA (id_empleado, fecha);
CREATE INDEX idx_inconsistencia_asistencia_estado ON INCONSISTENCIA (id_asistencia, estado);
CREATE INDEX idx_permiso_empleado_fechas ON PERMISO (id_empleado, fecha_inicio, fecha_fin);
CREATE INDEX idx_vacacion_empleado_fechas ON VACACION (id_empleado, fecha_inicio, fecha_fin);
CREATE INDEX idx_auditoria_entidad_fecha ON AUDITORIA (entidad, id_entidad, fecha_hora DESC);

INSERT INTO ROL (nombre) VALUES
  ('administrador'),
  ('recursos_humanos'),
  ('supervisor'),
  ('empleado')
ON CONFLICT (nombre) DO NOTHING;

COMMIT;
